//храним типы actions

export const GET_EXCHANGE_DATA_UAH_TO_CURRENCY = 'GET_EXCHANGE_DATA_UAH_TO_CURRENCY';
export const GET_EXCHANGE_DATA_CURRENCY_TO_UAH = 'GET_EXCHANGE_DATA_CURRENCY_TO_UAH';
export const GET_EXCHANGE_DATA_CURRENCY_TO_CURRENCY = 'GET_EXCHANGE_DATA_CURRENCY_TO_CURRENCY';
export const DELETE_EXCHANGE_DATA = 'DELETE_EXCHANGE_DATA';


